services:
  db:
    image: postgres:15
    container_name: dublin_rent_postgres
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: dublin_rent_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - /app/.venv # Avoid overwriting by local volume
      - ./backend:/app
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: dublin_rent_frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
